### PR TITLE
Change top letters and titles for long values

### PR DESCRIPTION
**Pull request by MarAvFe**
This PR is motivated for the possibility to add external i18n to the picker, as discussed in #15

### CODE REVIEW

**Comment by MarAvFe** [comment]
Welp. I couldn't run the tests on my pc, might be some local config thing. Anyway, if you can, you're free to add it, it was to test the default values for the names.

**Comment by MarAvFe** [comment]
Yes. It has the same default values. What it does is define a whole word for the top letters but only show the first one, and add the rest as a title (mouse hovered). If you were to send a wrong `letters` object as parameter, it ignores it. If you send only 3 or 0 properties, it leaves the rest unchanged.

```javascript
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-root',
  template: `
    <ngx-duration-picker
      [(value)]="myNegativeValue" 
      [options]="{ letters: letters }">
    </ngx-duration-picker>`,
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {

  myValue;
  myNegativeValue;
  showNegative = true;
  disabled = false;
  form: FormGroup;

  letters = {
    years: 'Años',
    months: 'Meses',
    days: 'Días',
    hours: 'Horas',
  };

  ngOnInit() {
    this.form = new FormGroup({
      'myDurationControl': new FormControl(null),
    });
  }
}
```

This would show the top letters as:
```
Y M W D H M S    Default
↓ ↓ ↓ ↓ ↓ ↓ ↓
A M - D H - -    Received parameters
↓ ↓ ↓ ↓ ↓ ↓ ↓
A M W D H M S    Result
```

**Comment by FrancescoBorzi** [comment]
@MarAvFe looks good. However I noticied you put the `letters` in the `Negative values` of the demo app (`src/`), I think it's better to create a new group to test those and add the test cases.

Can you please do it as well? So we can merge it

**Comment by MarAvFe** [comment]
Ok, will do.

**Comment by FrancescoBorzi** [comment]
@MarAvFe still alive?

**Comment by olarra** [comment]
Can this be merged?

**Comment by FrancescoBorzi** [comment]
I'm waiting for @MarAvFe

**Comment by MarAvFe** [comment]
Well, i'd totally forgot about it. Give me a couple of days to sort it out

**Comment by superdyzio** [comment]
@MarAvFe are you going to finish work regarding this? or can I take it from here?

**Comment by MarAvFe** [comment]
Please go ahead.

**Comment by superdyzio** [comment]
@FrancescoBorzi you think I can join the demo for this feature with `PreviewFormat` demo or better to create separate one?

**Comment by superdyzio** [comment]
@MarAvFe @FrancescoBorzi I think this can be closed now, #105 implemented that

**Pull request closed without merging**
